"""MCP server exposing the multi-agent swarm as tool-callable endpoints.

Provides FastMCP-based tooling so any MCP-compatible client can trigger
pipeline runs, inspect agent state, query shared memory, and retrieve
generated artefacts.  Supported transports: stdio, SSE, streamable-http.
"""

# ── Standard library ────────────────────────────────────────────────────────
import asyncio
import json
import os
import sys
import threading
from pathlib import Path
from typing import Optional

from mcp.server.fastmcp import FastMCP

# ── MCP server instance ─────────────────────────────────────────────────────
mcp = FastMCP(
    "hackathon-ibm",
    instructions=(
        "This server exposes a multi-agent software delivery swarm. "
        "Use 'run_swarm' to launch the full pipeline from a specification. "
        "Use the other tools to inspect progress, read outputs, etc."
    ),
)

# ── Shared module-level state ───────────────────────────────────────────────
_provider_name: Optional[str] = None
_model_name: Optional[str] = None
_swarm_running = False
_swarm_lock = threading.Lock()


def _configure(provider: Optional[str], model: Optional[str]):
    """Store provider and model names for deferred LLM initialisation.

    Args:
        provider: LLM provider identifier (e.g. ``"snowflake"``).
        model: Model name override; ``None`` falls back to env config.
    """
    global _provider_name, _model_name
    _provider_name = provider
    _model_name = model


# ── MCP tools ───────────────────────────────────────────────────────────────


@mcp.tool(
    description=(
        "Run the full multi-agent software delivery swarm on a project specification. "
        "Returns a summary when the pipeline completes (verdict, generated files, etc.). "
        "This is a long-running operation."
    )
)
def run_swarm(specs: str) -> str:
    """Execute the full multi-agent pipeline for a project specification.

    Args:
        specs: Free-text project specification describing the desired software.

    Returns:
        JSON summary containing the reviewer verdict, generated file list,
        and blackboard keys, or an error string on failure.
    """
    global _swarm_running

    with _swarm_lock:
        if _swarm_running:
            return "ERROR: A swarm run is already in progress. Wait for it to finish."
        _swarm_running = True

    try:
        import main as swarm_main

        if swarm_main._LLM_AVAILABLE and swarm_main.LLMRouter:
            if _provider_name:
                swarm_main._llm_provider = swarm_main.LLMRouter.create(
                    _provider_name, model=_model_name
                )
            else:
                swarm_main._llm_provider = swarm_main.LLMRouter.from_env()

        swarm_main._use_rich_display = False
        swarm_main._use_web_ui = False

        asyncio.run(swarm_main.run_swarm(specs, use_rich=False))

        verdict = swarm_main._blackboard.get("reviewer_verdict", "N/A")
        files = _list_output_files()
        summary = {
            "verdict": verdict,
            "output_files": files,
            "blackboard_keys": list(swarm_main._blackboard.keys()),
        }
        return json.dumps(summary, indent=2, default=str)

    except Exception as e:
        return f"ERROR: Swarm failed — {e}"

    finally:
        with _swarm_lock:
            _swarm_running = False


@mcp.tool(description="Get the current blackboard state (shared inter-agent memory).")
def get_blackboard() -> str:
    """Serialise every blackboard entry to a JSON string.

    Returns:
        JSON object of all key-value pairs, or an error string.
    """
    try:
        import main as swarm_main

        with swarm_main._bb_lock:
            bb = dict(swarm_main._blackboard)
        return json.dumps(bb, indent=2, default=str)
    except Exception as e:
        return f"ERROR: {e}"


@mcp.tool(description="Get the lifecycle status of every agent in the swarm.")
def get_agent_status() -> str:
    """Collect and return each agent's lifecycle state.

    Returns:
        JSON mapping of agent name to state string, or an error string.
    """
    try:
        import main as swarm_main

        statuses = {}
        for name in swarm_main.AGENT_CONFIGS:
            state = swarm_main._agent_states.get(name, "UNKNOWN")
            statuses[name] = str(state.value) if hasattr(state, "value") else str(state)
        return json.dumps(statuses, indent=2)
    except Exception as e:
        return f"ERROR: {e}"


@mcp.tool(description="List all files generated by the swarm in the output/ directory.")
def list_output_files() -> str:
    """Enumerate generated artefacts under the output directory.

    Returns:
        JSON array of POSIX-style relative paths.
    """
    return json.dumps(_list_output_files(), indent=2)


@mcp.tool(description="Read the content of an output file generated by the swarm.")
def read_output_file(path: str) -> str:
    """Read a single artefact from the output directory.

    Args:
        path: POSIX-style path relative to ``output/``.

    Returns:
        File content as UTF-8 text, or an error string.
    """
    output_root = Path("./output").resolve()
    target = (output_root / path).resolve()

    if not str(target).startswith(str(output_root)):
        return "ERROR: path traversal detected — access denied."

    if not target.exists():
        return f"ERROR: file not found — {path}"
    if not target.is_file():
        return f"ERROR: not a file — {path}"

    try:
        return target.read_text(encoding="utf-8", errors="replace")
    except Exception as e:
        return f"ERROR reading file: {e}"


@mcp.tool(description="Search the swarm's hybrid long-term memory (BM25 + semantic).")
def search_memory(query: str, top_k: int = 5) -> str:
    """Query the hybrid BM25 + semantic vector memory store.

    Args:
        query: Natural-language search string.
        top_k: Maximum number of results to return.

    Returns:
        JSON array of matching memory entries, or an error string.
    """
    try:
        import main as swarm_main

        if swarm_main._memory is None:
            return "Memory not initialized (swarm has not run yet)."
        results = swarm_main._memory.search(query, top_k=top_k)
        return json.dumps(results, indent=2, default=str)
    except Exception as e:
        return f"ERROR: {e}"


@mcp.tool(description="Get the event log of agent activity (last N events).")
def get_event_log(last_n: int = 30) -> str:
    """Retrieve the most recent entries from the agent event log.

    Args:
        last_n: Number of trailing events to return.

    Returns:
        JSON array of event dicts, or an error string.
    """
    try:
        import main as swarm_main

        with swarm_main._event_lock:
            events = list(swarm_main._event_log[-last_n:])
        return json.dumps(events, indent=2, default=str)
    except Exception as e:
        return f"ERROR: {e}"


# ── Helpers ─────────────────────────────────────────────────────────────────


def _list_output_files() -> list[str]:
    """Walk ``output/`` recursively and return POSIX-relative file paths."""
    output_root = Path("./output").resolve()
    if not output_root.exists():
        return []
    return [
        str(p.relative_to(output_root)).replace("\\", "/")
        for p in output_root.rglob("*")
        if p.is_file()
    ]


# ── Entry point ─────────────────────────────────────────────────────────────


def start_mcp_server(
    transport: str = "stdio",
    host: str = "127.0.0.1",
    port: int = 8000,
    provider: Optional[str] = None,
    model: Optional[str] = None,
):
    """Initialise LLM config and start the MCP server.

    Args:
        transport: Wire protocol (``"stdio"``, ``"sse"``, or
            ``"streamable-http"``).
        host: Bind address for network transports.
        port: Bind port for network transports.
        provider: LLM provider identifier forwarded to the swarm.
        model: Model name override.
    """
    _configure(provider, model)

    print(f"  MCP Server: transport={transport}", file=sys.stderr, flush=True)
    if transport in ("sse", "streamable-http"):
        print(
            f"  MCP Server: listening on http://{host}:{port}",
            file=sys.stderr,
            flush=True,
        )

    if transport == "stdio":
        mcp.run(transport="stdio")
    elif transport == "sse":
        mcp.run(transport="sse", host=host, port=port)
    elif transport == "streamable-http":
        mcp.run(transport="streamable-http", host=host, port=port)
    else:
        print(f"ERROR: unknown transport '{transport}'. Use stdio|sse|streamable-http")
        sys.exit(1)
